apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: idurar
type: Opaque
stringData:
  DATABASE: "mongodb://root:rootpassword@mongodb:27017/idurar?authSource=admin"
  JWT_SECRET: "your_private_jwt_secret_key"
  NODE_ENV: "development"
  OPENSSL_CONF: '/dev/null'
  PUBLIC_SERVER_FILE: "http://localhost:4000/"
  PORT: "4000"
