apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: backend-cpu-hog-chaos
  namespace: litmus
spec:
  engineState: active
  chaosServiceAccount: litmus

  appinfo:
    appns: idurar
    applabel: "backend"
    appkind: deployment

  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            - name: CPU_CORES
              value: "1"
            - name: TOTAL_CHAOS_DURATION
              value: "120"
