apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: backend-pod-delete-chaos
  namespace: litmus
spec:
  engineState: active
  chaosServiceAccount: litmus

  chaosResult:
    name: backend-pod-delete-chaos-result

  appinfo:
    appns: idurar
    applabel: "app=backend"
    appkind: deployment

  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "90"
            - name: CHAOS_INTERVAL
              value: "15"
            - name: PODS_AFFECTED_PERC
              value: "50"
            - name: TARGET_CONTAINER
              value: ""
            - name: CONTAINER_RUNTIME
              value: "containerd"
            - name: SOCKET_PATH
              value: "/run/containerd/containerd.sock"
            - name: RAMP_TIME
              value: "30"
            - name: LIB_IMAGE
              value: "litmuschaos/go-runner:3.0.0"
