apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: mongodb-cpu-exec-chaos
  namespace: litmus
spec:
  engineState: active
  chaosServiceAccount: litmus

  appinfo:
    appns: idurar
    applabel: "app=mongodb"
    appkind: statefulset

  experiments:
    - name: container-exec
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: mongodb

            - name: COMMAND
              value: |
                echo "Starting CPU stress"
                end=$((SECONDS+120))
                while [ $SECONDS -lt $end ]; do
                  : 
                done
                echo "CPU stress completed"

            - name: TOTAL_CHAOS_DURATION
              value: "120"
