name: Snyk Secret Scanning

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Snyk CLI
        run: npm install -g snyk 

      - name: Run Snyk secret scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Reference the GitHub secret
        run: |
          snyk code test --sarif-file-output=snyk.sarif || true # The '|| true' allows the workflow to continue even if vulns are found
      
      - name: Upload Snyk scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          wait-for-processing: true
